permalink: /:categories/:title
auto: true
markdown: kramdown
exclude: Rakefile, CNAME, sass/, script/, README.md

url: http://arungm29.github.com/

name: "Arun Mahadevan"
tagline: "Learning to Code"
description: "Notes by a developer"
about: "I'm <strong>Arun</strong>. I like coding, writing and designing for the web. I also happen to be a strong supporter of women's rights, and the LGBT community."
author:
 name: "Arun Mahadevan"
 email: "arungm29@gmail.com"
 github: "arungm29"
 twitter: "ArunMahadevan"
 facebook: "arun.mahadevan1"
comments :
  provider : disqus
  disqus :
    short_name : arunmahadevan
